"""add fields to payments

Revision ID: 04e6ac0f42b2
Revises: 8221b9643424
Create Date: 2022-11-19 23:01:13.929913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e6ac0f42b2'
down_revision = '8221b9643424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('intent_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('client_secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'client_secret')
    op.drop_column('payments', 'intent_id')
    # ### end Alembic commands ###
