"""add is_paid to payments

Revision ID: 50b746cf6f26
Revises: 02ea9b8709a7
Create Date: 2022-11-14 19:59:00.194847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b746cf6f26'
down_revision = '02ea9b8709a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('is_paid', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_payments_is_paid'), 'payments', ['is_paid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_is_paid'), table_name='payments')
    op.drop_column('payments', 'is_paid')
    # ### end Alembic commands ###
