"""Add roles to subscriptions

Revision ID: cf9a7a39a668
Revises: 3dde441846ca
Create Date: 2022-11-22 18:46:12.441132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf9a7a39a668'
down_revision = '3dde441846ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events_y2022m11')
    op.add_column('subscriptions', sa.Column('roles', sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'roles')
    op.create_table('events_y2022m11',
    sa.Column('payment_system_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('received_at', name='events_y2022m11_pkey')
    )
    # ### end Alembic commands ###
