"""add paymenttoptocess tabel

Revision ID: e0ac5634055a
Revises: 04e6ac0f42b2
Create Date: 2022-11-20 15:51:25.486186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0ac5634055a'
down_revision = '04e6ac0f42b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymentstoprocess',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('payment_intent', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paymentstoprocess_id'), 'paymentstoprocess', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paymentstoprocess_id'), table_name='paymentstoprocess')
    op.drop_table('paymentstoprocess')
    # ### end Alembic commands ###
