"""add completed field for paymentstoprocess

Revision ID: e4e8e076c1df
Revises: e0ac5634055a
Create Date: 2022-11-21 21:17:55.518084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4e8e076c1df'
down_revision = 'e0ac5634055a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paymentstoprocess', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paymentstoprocess', 'completed')
    # ### end Alembic commands ###
